apiVersion: v1
kind: Service
metadata:
  name: my-spring-app
spec:
  ports:
  - port: 8080
  selector:
    app: my-spring-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-spring-app
spec:
  selector:
    matchLabels:
      app: my-spring-app
  template:
    metadata:
      labels:
        app: my-spring-app
    spec:
      containers:
        - name: my-spring-app
          image: dbrudghks333/slackapp:8.0
          ports:
          - containerPort: 8080
          envFrom:
          - configMapRef:
              name: my-spring-app-config